mount tags tentatively resolved
mount tags transfer to/from between mounts and are added/removed correctly by source
error: weapon tags can incorrectly generate mount tags when dragged onto mounts